name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: messaging_app_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_NAME: messaging_app_test
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        id: wait_mysql
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -utestuser -ptestpass && exit 0
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL not available, will use SQLite"
          exit 1
        continue-on-error: true

      - name: Run Django tests
        run: |
          if [ "${{ steps.wait_mysql.outcome }}" == "success" ]; then
            echo "Using MySQL database"
            python manage.py migrate
            python manage.py test
          else
            echo "Falling back to SQLite"
            export DATABASE_NAME=db.sqlite3
            python manage.py migrate
            python manage.py test
