pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "akinscoded/messaging_app"
    }

    stages {
        stage('Preparation') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:Akins-Coded/alx-backend-python.git',
                    credentialsId: 'github-ssh'
            }
        }

        stage('Build') {
            steps {
                echo "Building..."
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                  docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ./messaging_app
                  docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest
                """
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh "echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                  docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                  docker push ${DOCKER_IMAGE}:latest
                """
            }
        }
    }

    post {
        always {
            sh "docker logout"
            cleanWs()
        }
    }
}
