#!/bin/bash

# Deploy blue and green versions
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

# Check logs for green deployment
kubectl logs -l app=messaging-app,version=green --tail=20

# To switch service to green
kubectl patch service messaging-app-service -p '{"spec":{"selector":{"app":"messaging-app","version":"green"}}}'

# Optional: scale down blue after switch
kubectl scale deployment messaging-app-blue --replicas=0
